config/routes.rb
Rails.application.routes.draw do
#  get 'users/show'
get 'search', to: 'search#search'
  devise_for :users
#  resources :users
  resources :movies do 
  resources :movie_genres  do 
    member { post :vote }
  resources :movie_genre_comments, shallow: true do
    member { post :vote }
      end
    end
  resources :movie_themes do 
    member { post :vote }
  resources :movie_theme_comments, shallow: true do
    member { post :vote }
  
  
    end
  end
end
      


   
 

  
   root 'movies#index'


end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  
  def search
  if params[:q].nil?
    @movie_genres = []
    @movie_themes = []
    @movies       = []
  else
    @movie_genres = MovieGenre.search params[:q]
    @movie_themes = MovieTheme.search params[:q]
    @movies = Movie.search params[:q]
  end
end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.erb
cd <h1>Search Results</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>
 
<strong>Genres:
<% @movie_genres.each do |movie_genre| %>
<%= link_to movie_genre.title, movie_movie_genres_path(movie_genre.movie_id) %>
<!-- <%= link_to movie_genre.title, movie_movie_genres_path(movie_genre.movie_id) %> -->
  
    <% end %>

<br />
Themes:
<% @movie_themes.each do |movie_theme| %>
<%= link_to movie_theme.title, movie_movie_themes_path(movie_theme.movie_id) %>
    <% end %>
<br />
Movies:
<% @movies.each do |movie| %>
  <%= link_to movie.title, movies_path(@movies) %>
    <% end %>
</strong>