config/routes.rb
Rails.application.routes.draw do
#  get 'users/show'
get 'search', to: 'search#search'
  devise_for :users
#  resources :users
  resources :movies do 
  resources :movie_genres  do 
    member { post :vote }
  resources :movie_genre_comments, shallow: true do
    member { post :vote }
      end
    end
  resources :movie_themes do 
    member { post :vote }
  resources :movie_theme_comments, shallow: true do
    member { post :vote }
  
  
    end
  end
end
      


   
 

  
   root 'movies#index'


end

app/models/movie_theme.rb
require 'elasticsearch/model'
class MovieTheme < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :user
  belongs_to :movie
  has_many :movie_theme_comments
  
  has_reputation :votes, source: :user, aggregated_by: :sum
 
  def self.popular
    reorder('votes desc').order('created_at DESC').find_with_reputation(:votes, :all)
  end  
  
end
MovieTheme.import

app/controllers/movie_themes_controller.rb
class MovieThemesController < ApplicationController
  before_action :set_movie_theme, only: [:show, :edit, :update, :destroy, :votes]
  before_action :set_movie
  before_action :authenticate_user!, except: [:index, :show]
  
  respond_to :html

  def index
    @movie_themes = MovieTheme.all
 
  end
  
  def show
    @movie_theme_comments = MovieThemeComment.where(movie_theme_id: @movie_theme.id)
 
  end
  
   def vote
     value = params[:type] == "up" ? 1 : -1
     @movie_theme = MovieTheme.find(params[:id])
     @movie_theme.add_or_update_evaluation(:votes, value, current_user)
     redirect_to :back, notice: "thanks for the vote"
   end

  def new
    @movie_theme = MovieTheme.new
    respond_with(@movie_theme)
  end

  def edit
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @movie_theme = @movie.movie_themes.create(movie_theme_params)
    @movie_theme.user_id = current_user.id
    
    if @movie_theme.save
      redirect_to @movie
    else
      render 'new'
    end
end

  def update
    @movie_theme.update(movie_theme_params)
    respond_with(@movie_theme)
  end

  def destroy
    @movie_theme.destroy
    respond_with(@movie_theme)
  end

  private
    def set_movie_theme
      @movie_theme = MovieTheme.find(params[:id])
    end
  
  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

    def movie_theme_params
      params.require(:movie_theme).permit(:title, :description)
    end
end

app/helpers/movie_themes_helper.rb
module MovieThemesHelper
end

app/views/movie_themes/_comment.html.erb
<div class="container-fluid">
  <div class="panel panel-default">
    <table class="table table-hover">

    <h3>Comments</h3>
      <% @movie_theme_comments.popular.each do |movie_theme_comment| %>
      <tr><td><strong><%= movie_theme_comment.title %></strong></td>
  
 
        <td><%= movie_theme_comment.description %></td>

        <td><%= link_to vote_movie_theme_comment_path(movie_theme_comment, type: "up"), method: "post", class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-arrow-up"></i>
        <% end %></td>
  
        <td><h2><%= pluralize movie_theme_comment.reputation_for(:votes).to_i, "" %></h2></td>
        <td> <%= link_to vote_movie_theme_comment_path(movie_theme_comment, type: "down"), method: "post", class: "btn btn-default" do %>
     <i class="glyphicon glyphicon-arrow-down"></i><% end %></td> 
     

   
  <% end %>
       

        <td><%= link_to "Add new comment", new_movie_movie_theme_movie_theme_comment_path(@movie, @movie_theme) %></td></tr>
    </table>
  </div>
</div>

app/views/movie_themes/_form.html.erb
<%= form_for([@movie, @movie_theme]) do |f| %>
  <% if @movie_theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_theme.errors.count, "error") %> prohibited this movie_theme from being saved:</h2>

      <ul>
      <% @movie_theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_themes/edit.html.erb
<h1>Editing movie_theme</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_theme %> |
<%= link_to 'Back', movie_themes_path %>

app/views/movie_themes/index.html.erb
<h1>Listing movie_themes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_themes.each do |movie_theme| %>
      <tr>
        <td><%= movie_theme.title %></td>
        <td><%= movie_theme.description %></td>
        <td><%= link_to 'Show', movie_theme %></td>
        <td><%= link_to 'Edit', edit_movie_theme_path(movie_theme) %></td>
        <td><%= link_to 'Destroy', movie_theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie theme', new_movie_theme_path %>

app/views/movie_themes/new.html.erb
<h1>New movie_theme</h1>

<%= render 'form' %>

app/views/movie_themes/show.html.erb
<div class="container-fluid">
  <div class="panel panel-default">
  <div class="row">
    <div class="col-xs-6"><strong>Movie:</strong>
    <%= link_to @movie.title, movie_path(@movie) %></div>
    </div>
    <div class="row">
    <div class="col-xs-6"><strong>Genre:</strong>
      <%= @movie_theme.title %> <span class="badge"><%= pluralize @movie_theme.reputation_for(:votes).to_i, "" %></strong></div>
    </div>
            <div class="row">
    <div class="col-xs-6"> <strong>Description:</strong>
      <%= @movie_theme.description %></div>
    </div>

                

    </div>
            </div>
         
            </div>
</div>
<%= render 'comment' %>