config/routes.rb
Rails.application.routes.draw do
#  get 'users/show'
get 'search', to: 'search#search'
  devise_for :users
#  resources :users
  resources :movies do 
  resources :movie_genres  do 
    member { post :vote }
  resources :movie_genre_comments, shallow: true do
    member { post :vote }
      end
    end
  resources :movie_themes do 
    member { post :vote }
  resources :movie_theme_comments, shallow: true do
    member { post :vote }
  
  
    end
  end
end
      


   
 

  
   root 'movies#index'


end

app/models/movie_genre.rb
require 'elasticsearch/model'
class MovieGenre < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  belongs_to :user
  belongs_to :movie
  has_many :movie_genre_comments
  

  has_reputation :votes, source: :user, aggregated_by: :sum
  
#  scope :similar_themes, 
  def self.popular
    reorder('votes desc').order('created_at DESC').find_with_reputation(:votes, :all)
  end 
  
#  def self.similar_theme
#    @similar_themes = MovieTheme ->(movie_theme) { where("id != ? and movie_theme_id = ?", movie_theme.id, movie_theme.movie_theme_id) }  
 # end

end
MovieGenre.import

app/controllers/movie_genres_controller.rb
class MovieGenresController < ApplicationController
  before_action :set_movie_genre, only: [:show, :edit, :update, :destroy, :votes]
  before_action :set_movie
  before_action :authenticate_user!, except: [:index, :show]
  
  respond_to :html

  def index
   # @movies = Movie.find(params[:movie_id])
    @movie_genres = MovieGenre.where(movie_id: @movie.id)
   # @movie_genres = MovieGenre.all
   
   
   
  end

  def show
    @movie_genre_comments = MovieGenreComment.where(movie_genre_id: @movie_genre.id)
   # @movie_genre = MovieGenre.where(movie_id: @movie.id)

  end

     def vote
      value = params[:type] == "up" ? 1 : -1
       @movie_genre = MovieGenre.find(params[:id])
       @movie_genre.add_or_update_evaluation(:votes, value, current_user)
      redirect_to :back, notice: "thanks for the vote"
   end

  def new
    @movie_genre = MovieGenre.new
    respond_with(@movie_genre)
  end

  def edit
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @movie_genre = @movie.movie_genres.create(movie_genre_params)
    @movie_genre.user_id = current_user.id
    
    if @movie_genre.save
      redirect_to @movie
    else
      render 'new'
    end
end

  def update
    @movie_genre.update(movie_genre_params)
    respond_with(@movie_genre)
  end

  def destroy
    @movie_genre.destroy
    respond_with(@movie_genre)
  end

  private
    def set_movie_genre
      @movie_genre = MovieGenre.find(params[:id])
    end
  
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    def movie_genre_params
      params.require(:movie_genre).permit(:title, :description)
    end
end

app/helpers/movie_genres_helper.rb
module MovieGenresHelper
end

app/views/movie_genres/_comment.html.erb
<div class="container-fluid">
  <div class="panel panel-default">
    <table class="table table-hover">

    <h3>Comments</h3>
      <% @movie_genre_comments.popular.each do |movie_genre_comment| %>
  <tr><td><strong><%= movie_genre_comment.title %></strong></td>
  
 
  <td><%= movie_genre_comment.description %></td>

      <td><%= link_to vote_movie_genre_comment_path(movie_genre_comment, type: "up"), method: "post", class: "btn btn-default" do %>
    <i class="glyphicon glyphicon-arrow-up"></i>
        <% end %></td>
  
    <td><h2><%= pluralize movie_genre_comment.reputation_for(:votes).to_i, "" %></h2></td>
   <td> <%= link_to vote_movie_genre_comment_path(movie_genre_comment, type: "down"), method: "post", class: "btn btn-default" do %>
     <i class="glyphicon glyphicon-arrow-down"></i><% end %></td> 
     

   
  <% end %>
       

<td><%= link_to "Add new comment", new_movie_movie_genre_movie_genre_comment_path(@movie, @movie_genre) %></td></tr>
    </table>
  </div>
</div>


    
                
      
             
                

app/views/movie_genres/_form.html.erb
<%= form_for([@movie, @movie_genre]) do |f| %>
  <% if @movie_genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie_genre.errors.count, "error") %> prohibited this movie_genre from being saved:</h2>

      <ul>
      <% @movie_genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movie_genres/edit.html.erb
<h1>Editing movie_genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie_genre %> |
<%= link_to 'Back', movie_genres_path %>

app/views/movie_genres/index.html.erb
<h1>Genre Results</h1>

<table>
  <thead>
    <tr>
      <th>Votes</th>
      <th>Title</th>
      <th>Votes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_genres.popular.each do |movie_genre| %>
      <tr>
        <td><%= @movie.title %>
        <td><%= link_to movie_genre.title, movie_movie_genre_path(@movie, movie_genre) %></td>
        <td><%= pluralize movie_genre.reputation_for(:votes).to_i, "" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movie_genres/new.html.erb
<h1>New movie_genre</h1>

<%= render 'form' %>

app/views/movie_genres/show.html.erb
<div class="container-fluid">
  <div class="panel panel-default">
  <div class="row">
    <div class="col-xs-6"><strong>Movie:</strong>
    <%= link_to @movie.title, movie_path(@movie) %></div>
    </div>
    <div class="row">
    <div class="col-xs-6"><strong>Genre:</strong>
<%= @movie_genre.title %> <span class="badge"><%= pluralize @movie_genre.reputation_for(:votes).to_i, "" %></strong></div>
    </div>
            <div class="row">
    <div class="col-xs-6"> <strong>Description:</strong>
<%= @movie_genre.description %></div>
    </div>
       <div class="row">
    <div class="col-xs-6"> <strong>Submitted by:</strong>
      <%= @movie_genre.user_id %></div>
    </div>
                

    </div>
            </div>
         
            </div>
</div>
<%= render 'comment' %>
<br />
Testing